#COMPOSE SCREENS

version: "2"
services:
  #####################################################################################################
  editor:
    image: jonimoas/cmssimple_editor:0.2
    container_name: cmssimple_editor
    restart: always
    ports:
      - "2000:2000"
    environment:
      EDITOR_PORT: 2000
      HOST:
  cms:
    image: jonimoas/cmssimple:0.2
    container_name: cmssimple
    restart: always
    environment:
      HOST:
      NAME:
      ADMIN_PASSWORD:
      PORT: 80
    ports:
      - "80:80"
  #####################################################################################################
