#COMPOSE SCREENS

version: "2"
services:
  #####################################################################################################
  cms:
    image: jonimoas/cmssimple:0.3
    container_name: cmssimple
    restart: always
    environment:
      HOST:
      NAME:
      ADMIN_PASSWORD:
      MAIN_PORT: 8023
      NEW_PORT: 80
    ports:
      - "8023:80"
  #####################################################################################################
